# Generated by Django 5.2.8 on 2025-11-19 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_created_date_alter_tasks_deleted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
