# Generated by Django 5.2.8 on 2025-11-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_user_options_alter_tasks_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-due_date', '-id']},
        ),
    ]
