# Generated by Django 5.2.8 on 2025-11-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['due_date', '-id']},
        ),
    ]
